services:
  # 1. La Base de Données
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: surfadmin
      POSTGRES_DB: cs2manager
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 2. La File d'Attente
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # 3. Ton API FastAPI
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8080:8000"
    volumes:
      - ./backend:/app # Magie : Tes changements de code seront pris en compte en direct !
    environment:
      # Dans Docker, "localhost" ne marche plus. On utilise le nom des services (db, redis)
      - DATABASE_URL=postgresql+psycopg://postgres:surfadmin@db/cs2manager
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  # 4. Le Worker Celery (Les bras)
  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A app.worker.celery_app worker --loglevel=info
    volumes:
      - ./backend:/app
      # LE SECRET : On donne accès au moteur Docker de la machine hôte au Worker
      - /var/run/docker.sock:/var/run/docker.sock 
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:surfadmin@db/cs2manager
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  # 5. Le Beat Celery (Le métronome pour l'Auto-Kill)
  beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A app.worker.celery_app beat --loglevel=info
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:surfadmin@db/cs2manager
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  # 6. L'Image de Base CS2 (Nouveau !)
  # Ce service ne lance rien au démarrage (pas de ports, pas de command).
  # Il sert uniquement à dire à Docker Compose comment construire l'image 
  # que le Worker appellera plus tard.
  cs2-base:
    build:
      context: .
      dockerfile: docker/Dockerfile.real
    image: cs2-surf-base:latest # <-- C'est le nom exact que ton worker.py recherche

volumes:
  pgdata: